user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }
Page_Membre:
    path:     /pageMembre
    defaults: { _controller: UserBundle:Default:Membre }

Page_Admin:
    path:     /admin
    defaults: { _controller: UserBundle:Default:Admin }

Page_Responsable:
    path:     /pageResponsable
    defaults: { _controller: UserBundle:Default:Responsable }
