<?php

namespace GestionEntretienBundle\Repository;

/**
 * entretienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class entretienRepository extends \Doctrine\ORM\EntityRepository
{
}
