<?php

namespace BlogBundle\Repository;

/**
 * LikedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikedRepository extends \Doctrine\ORM\EntityRepository
{
}
